name: Release

on:
  push:
    tags: ['v*']

jobs:
  release-ter:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: intl, mbstring, json, zip, curl
          tools: composer:v2, typo3/tailor, clue/phar-composer

      - name: Set version output
        id: vars
        run: |
          v=${GITHUB_REF#refs/tags/v}
          t=${GITHUB_REF#refs/tags/}
          echo "version=${v}" >> $GITHUB_OUTPUT
          echo "tag=${t}" >> $GITHUB_OUTPUT

      - name: Create artifact
        run: |
          make release RELEASE_VERSION=${{ steps.vars.outputs.tag }}

      - name: Create github release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.vars.outputs.tag }}
          body_path: release/changelog.md
          files: |
            release/supi.zip
